import { useMemo, useState, type ReactNode } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { DollarSign, Wallet, Plus, Settings, ArrowUpDown, Save } from "lucide-react";
import { loadMMSettings, saveMMSettings, loadMMTransactions, saveMMTransactions, loadMMAdjustments, computeMMRows, formatBase, estimateCommission } from "@/lib/mobileMoney";
import type { MMSettings, MMTransaction, MMOperation } from "@/types/mobileMoney";
import { useRBAC } from "@/hooks/useRBAC";

export function MobileMoneyPanel() {
  const { userRole } = useRBAC();
  const canEdit = userRole !== "LECTURE_SEULE";
  const [settings,setSettings] = useState<MMSettings>(()=>loadMMSettings());
  const [transactions,setTransactions] = useState<MMTransaction[]>(()=>loadMMTransactions());
  const [selectedService,setSelectedService] = useState("ALL");
  const [newService,setNewService] = useState("");
  const [tx,setTx] = useState({service:settings.services[0]?.service ?? "MonCash",operation:"DEPOT" as MMOperation,montant:"",frais:"",commission:"",currency:settings.base_currency,note:""});
  const adjustments = loadMMAdjustments();
  const {rows,totals} = useMemo(()=>computeMMRows(transactions,adjustments,settings),[transactions,adjustments,settings]);
  const services = settings.services.map(s=>s.service);
  const visible = selectedService === "ALL" ? totals : totals.byService.find(s=>s.service===selectedService) ?? {cashActive:0,walletActive:0,honorairesNets:0,volumeDepots:0,volumeRetraits:0};
  const filteredRows = selectedService === "ALL" ? rows : rows.filter(r=>r.service===selectedService);
  const addService = () => { const name=newService.trim(); if(!name || services.includes(name)) return; const updated={...settings,services:[...settings.services,{service:name,opening_cash_base:0,opening_cash_usd:0,opening_wallet_base:0,opening_wallet_usd:0}]}; setSettings(updated); saveMMSettings(updated); setNewService(""); setSelectedService(name); };
  const updateBalance = (service:string,key:"opening_cash_base"|"opening_cash_usd"|"opening_wallet_base"|"opening_wallet_usd",value:number) => { const updated={...settings,services:settings.services.map(s=>s.service===service?{...s,[key]:value}:s)}; setSettings(updated); saveMMSettings(updated); };
  const addTransaction = () => { if(!canEdit) return; const amount=Number(tx.montant); if(amount<=0)return; const commission=Number(tx.commission)||((tx.operation==="DEPOT")?estimateCommission(amount,settings):0); const row:MMTransaction={id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10),service:tx.service,operation:tx.operation,montant:amount,frais_client:Number(tx.frais)||0,commission_operateur:commission,commission_estimee:!tx.commission,currency:tx.currency as any,note:tx.note||undefined,created_at:new Date().toISOString()}; const updated=[...transactions,row]; setTransactions(updated); saveMMTransactions(updated); setTx({...tx,montant:"",frais:"",commission:"",note:""}); };
  const syncAI = () => { if(typeof window!=="undefined") window.localStorage.setItem("scarwrite_mm_ai_context",JSON.stringify({updated_at:new Date().toISOString(),settings,selectedService,balances:totals.byService,transactions:filteredRows})); };
  return <div className="space-y-6 p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-serif text-[#0B1E48]">Mobile Money & Transferts</h2><p className="text-sm text-muted-foreground">Comptabilité isolée par service — Cash physique + Wallet numérique</p></div><div className="flex gap-2"><ServiceSettings settings={settings} onChange={s=>{setSettings(s);saveMMSettings(s)}} canEdit={canEdit} newService={newService} setNewService={setNewService} addService={addService} updateBalance={updateBalance}/><Button onClick={syncAI} variant="outline"><Save className="mr-2 h-4 w-4"/>Synchroniser avec Studio IA</Button></div></div>
    <div className="flex items-center gap-3"><Label>Service</Label><Select value={selectedService} onValueChange={setSelectedService}><SelectTrigger className="w-64"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ALL">Tous les services</SelectItem>{services.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>
    <div className="grid gap-4 md:grid-cols-3"><Kpi title="Caisse Cash Physique" value={formatBase(visible.cashActive,settings)} icon={<DollarSign/>}/><Kpi title="Portefeuille Numérique" value={formatBase(visible.walletActive,settings)} icon={<Wallet/>}/><Kpi title="Produits / CA net" value={formatBase(visible.honorairesNets,settings)} icon={<ArrowUpDown/>}/></div>
    <Card><CardHeader><CardTitle>Nouvelle transaction — {tx.service}</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-7"><Select value={tx.service} onValueChange={v=>setTx({...tx,service:v})} disabled={!canEdit}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{services.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Select value={tx.operation} onValueChange={v=>setTx({...tx,operation:v as MMOperation})} disabled={!canEdit}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="DEPOT">Dépôt / Envoi</SelectItem><SelectItem value="RETRAIT">Retrait / Réception</SelectItem></SelectContent></Select><Input type="number" placeholder="Montant client" value={tx.montant} onChange={e=>setTx({...tx,montant:e.target.value})} disabled={!canEdit}/><Input type="number" placeholder="Frais client Cash" value={tx.frais} onChange={e=>setTx({...tx,frais:e.target.value})} disabled={!canEdit}/><Input type="number" placeholder="Commission opérateur" value={tx.commission} onChange={e=>setTx({...tx,commission:e.target.value})} disabled={!canEdit}/><Input placeholder="Note" value={tx.note} onChange={e=>setTx({...tx,note:e.target.value})} disabled={!canEdit}/><Button onClick={addTransaction} disabled={!canEdit||!tx.montant}><Plus className="mr-2 h-4 w-4"/>Ajouter</Button></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Journal comptable et soldes calculés</CardTitle></CardHeader><CardContent><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-left">Date</th><th className="p-2 text-left">Service</th><th className="p-2 text-left">Opération</th><th className="p-2 text-right">Cash après</th><th className="p-2 text-right">Wallet après</th><th className="p-2 text-right">Produits</th></tr></thead><tbody>{filteredRows.map(r=><tr key={r.id} className="border-b"><td className="p-2">{r.date}</td><td className="p-2">{r.service}</td><td className="p-2"><Badge>{r.operation}</Badge></td><td className="p-2 text-right">{formatBase(r.solde_cash,settings)}</td><td className="p-2 text-right">{formatBase(r.solde_wallet,settings)}</td><td className="p-2 text-right">{formatBase(r.honoraire_net,settings)}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs text-muted-foreground">Dépôt/Envoi : Cash après = avant + montant + frais client ; Wallet après = avant - montant + commission opérateur. Retrait/Réception : Cash après = avant - montant ; Wallet après = avant + montant + commission opérateur. Le montant client est un mouvement compte-à-compte ; les produits sont limités aux frais client et commissions.</p></CardContent></Card>
  </div>;
}
function Kpi({title,value,icon}:{title:string,value:string,icon:ReactNode}){return <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-sm">{title}</CardTitle>{icon}</CardHeader><CardContent><div className="text-2xl font-bold text-[#0B1E48]">{value}</div></CardContent></Card>}
function ServiceSettings({settings,onChange,canEdit,newService,setNewService,addService,updateBalance}:{settings:MMSettings;onChange:(s:MMSettings)=>void;canEdit:boolean;newService:string;setNewService:(s:string)=>void;addService:()=>void;updateBalance:(service:string,key:"opening_cash_base"|"opening_cash_usd"|"opening_wallet_base"|"opening_wallet_usd",value:number)=>void}){const [open,setOpen]=useState(false);return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" disabled={!canEdit}><Settings className="mr-2 h-4 w-4"/>Paramètres</Button></DialogTrigger><DialogContent className="max-w-4xl max-h-[80vh] flex flex-col overflow-y-auto"><DialogHeader className="shrink-0"><DialogTitle>Caisses de départ — par service</DialogTitle></DialogHeader><Tabs defaultValue="caisses" className="flex min-h-0 flex-1 flex-col"><TabsList className="shrink-0"><TabsTrigger value="caisses">Caisses de Départ</TabsTrigger><TabsTrigger value="general">Général</TabsTrigger></TabsList><TabsContent value="general" className="mt-4 max-h-[60vh] overflow-y-auto pr-2 custom-scrollbar space-y-3"><Label>Devise de base</Label><Select value={settings.base_currency} onValueChange={v=>onChange({...settings,base_currency:v as any})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="HTG">HTG</SelectItem><SelectItem value="USD">USD</SelectItem><SelectItem value="EUR">EUR</SelectItem><SelectItem value="DOP">DOP</SelectItem><SelectItem value="CAD">CAD</SelectItem></SelectContent></TabsContent><TabsContent value="caisses" className="mt-4 max-h-[60vh] overflow-y-auto pr-2 custom-scrollbar space-y-4"><div className="flex shrink-0 gap-2"><Input placeholder="Nouveau service (Zelle, Unibank...)" value={newService} onChange={e=>setNewService(e.target.value)}/><Button onClick={addService} disabled={!canEdit||!newService.trim()}><Plus className="mr-2 h-4 w-4"/>Ajouter un Service</Button></div>{settings.services.map(s=><Card key={s.service}><CardHeader><CardTitle className="text-base">{s.service}</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><Field label={`Cash initial ${settings.base_currency}`} value={s.opening_cash_base} onChange={v=>updateBalance(s.service,"opening_cash_base",v)}/><Field label="Cash initial USD" value={s.opening_cash_usd} onChange={v=>updateBalance(s.service,"opening_cash_usd",v)}/><Field label={`Wallet initial ${settings.base_currency}`} value={s.opening_wallet_base} onChange={v=>updateBalance(s.service,"opening_wallet_base",v)}/><Field label="Wallet initial USD" value={s.opening_wallet_usd} onChange={v=>updateBalance(s.service,"opening_wallet_usd",v)}/></CardContent></Card>)}</TabsContent></Tabs><DialogFooter className="shrink-0 border-t pt-3"><Button type="button" onClick={()=>{saveMMSettings(settings);setOpen(false)}}><Save className="mr-2 h-4 w-4"/>Enregistrer</Button></DialogFooter></DialogContent></Dialog>}
function Field({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <div><Label>{label}</Label><Input type="number" value={value} onChange={e=>onChange(Number(e.target.value)||0)}/></div>}
